### ISSUE TITLE
Preprocessors ordering

### ISSUE THREAD

**Issue by vicioussn** [tpretz/terraform-provider-zabbix#25]
Hello,

Is there a way to sort 'preprocessor' block?

I was expecting that they will ordered in the way how are they ordered in the .tf file, but for some reason block with type="26" always trying to be at the first place.

**Comment by tpretz** [comment]
had a check, you are correct it ends up first regardless of how the api call is made
https://github.com/tpretz/terraform-provider-zabbix/commit/e6f32cb0100b421bc58564c20733daa05354965b

Doing some research tho
https://www.zabbix.com/documentation/5.4/en/manual/config/items/preprocessing
![image](https://user-images.githubusercontent.com/7040476/158479819-05cea642-9a46-43ab-b91c-64bad3fa7eda.png)

It does say it has to be used first
I could add understanding to the terraform module of this (and reject prior to apply) but to be honest there are so many specifics around pre-processors, its likely better off being covered as part of fully supporting them (abstracting the type numbers and becoming fully aware of their logic / parameters)

**Comment by vicioussn** [comment]
Ah ok, I was confused that manually I can set it to be on the last place. But yeah, docs make it clear.
