### ISSUE TITLE
Host Destruction fails on Zabbix 6.2

### ISSUE THREAD

**Issue by rdavisunr** [tpretz/terraform-provider-zabbix#29]
**Destroying hosts does not work with Zabbix 6.2**

As specified in the 2.2 manual for[ host.delete](https://www.zabbix.com/documentation/2.2/en/manual/api/reference/host/delete):
` The method can also accept an array of host objects with the hostid property defined. This format is deprecated.`

As of (at least) Zabbix v6.2, that method has indeed been deprecated. Instead, hosts must be specified as an array of hostids.

This causes the following failure when destroying hosts with [terraform-provider-zabbix](https://github.com/tpretz/terraform-provider-zabbix):
`Error: -32602 (Invalid params.): Invalid parameter "/1": a number is expected.`

**Deprecated Method used by terraform-provider-zabbix**
```json
{
    "jsonrpc": "2.0",
    "method": "host.delete",
    "params": [{
            "hostid": "10473"
        }
    ],
    "auth": "038e1d7b1735c6a5436ee9eae095879e",
    "id": 3
}
```
**Correct Method**
```json
{
    "jsonrpc": "2.0",
    "method": "host.delete",
    "params": ["10473"],
    "auth": "038e1d7b1735c6a5436ee9eae095879e",
    "id": 3
}
```

**Comment by vicioussn** [comment]
I confirm it does exist.

**Comment by tpretz** [comment]
should be fixed as of https://github.com/tpretz/terraform-provider-zabbix/releases/tag/v0.17.0

re-open if its still a problem
