### ISSUE TITLE
Provider No Longer works with 6.4 and above

### ISSUE THREAD

**Issue by wkleinhenz** [tpretz/terraform-provider-zabbix#30]
Mirroring the [issue ](https://github.com/claranet/terraform-provider-zabbix/issues/62) from another Zabbix Provider, this provider no longer works due to changes made to the API in 6.4, as they dropped support for the user parameter and instead require the use of the username parameter

**Comment by redzioch** [comment]
This problem is connected to go-zabbix-api, it was reported 2 weeks ago here:
https://github.com/tpretz/go-zabbix-api/pulls

**Comment by tpretz** [comment]
have not tested with version 6.4 yet, but should be fixed as of https://github.com/tpretz/terraform-provider-zabbix/releases/tag/v0.16.0

re-open if its still an issue
