### ISSUE TITLE
zabbix_template failing with: No permissions to referred object or it does not exist!

### ISSUE THREAD

**Issue by hongyecc** [tpretz/terraform-provider-zabbix#33]
I am trying to use the provider to create zabbix template but it is failing with above error. I am using zabbix6.4.

API User/Role:
```
{
  "name": "zabbix-api",
  "roleid": "3"
}
{
  "name": "Super admin role",
  "roleid": "3"
}
```
hostgroup:
```
terraform state show 'zabbix_hostgroup.zabbix["prod"]'
# zabbix_hostgroup.zabbix["prod"]:
resource "zabbix_hostgroup" "zabbix" {
    id   = "79"
    name = "prod"
}
```
terraform plan:
```
  # zabbix_template.zabbix["prod"] will be created
  + resource "zabbix_template" "zabbix" {
      + description = "prod"
      + groups      = [
          + "79",
        ]
      + host        = "prod"
      + id          = (known after apply)
      + name        = "prod"
}
```
terraform apply:
```

│ Error: -32500 (Application error.): No permissions to referred object or it does not exist!
│
│   with zabbix_template.zabbix["prod"],
│   on main.tf line 86, in resource "zabbix_template" "zabbix":
│   86: resource "zabbix_template" "zabbix" {

```
terraform version and providers:
```
Terraform v1.5.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/tpretz/zabbix v0.17.0
```
Any idea what the problem is?

**Comment by vicioussn** [comment]
Hi


This is because Zabbix now have two different types of groups - host groups and template groups. And our provider support only old type - host ones, I suppose.

For me to workaround this, I've created group separately and hardcoded group ID into TF code.

**Comment by hongyecc** [comment]
@vicioussn thanks for replying ... I tried to hardcode group id and it did not work for me. Which version of zabbix are you using? I am assuming TF version is not the problem. My wild guess is that it is either the provider or zabbix api.

**Comment by vicioussn** [comment]
On vacations now, will take a look in 1 week :(

Zabbix is 6.2.xxx

**Comment by hongyecc** [comment]
Ah .. seems the documentation is wrong ... the "groups" should be "templategroup" ids, not "hostgroup" ids.
(https://github.com/tpretz/terraform-provider-zabbix#zabbix_template)

Here is the zabbix document:
https://www.zabbix.com/documentation/6.2/en/manual/api/reference/template/create

I am not seeing a "templategroup" resource in this provider ... hmmm, probably this provider does not support zabbix6.2/6.4
